package com.evProService.repository;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

import com.evProService.base.TestBaseAppium;

public class ForgotPasswordScreen extends TestBaseAppium {
	
	
	public ForgotPasswordScreen() throws Exception {
		PageFactory.initElements(driver, this);
	}
	
	@FindBy(xpath="//android.widget.TextView[@text='Forgot Password']")
	WebElement forgotPasswordHeaderText;
	public WebElement forgotPasswordHeaderText()
	{
		return forgotPasswordHeaderText;
	}
	
	@FindBy(xpath="//android.widget.EditText[@index='0']")
	WebElement emailTextField;
	public WebElement emailTextField()
	{
		return emailTextField;
	}
	
	@FindBy(xpath="//android.widget.TextView[@text='Submit']")
	WebElement submitButton;
	public WebElement submitButton()
	{
		return submitButton;
	}
	
	@FindBy(xpath="//android.widget.TextView[@text='Sign In']")
	WebElement signInButton;
	public WebElement signInButton()
	{
		return signInButton;
	}
	
	@FindBy(xpath="//android.widget.ImageButton[@index='0']")
	WebElement backButton;
	public WebElement backButton()
	{
		return backButton;
	}
	
	@FindBy(xpath="//android.widget.TextView[@text='Mail with autogenerated password has been sent to your Email ID.']")
	WebElement passwordSentToMailText;
	public WebElement passwordSentToMailText()
	{
		return passwordSentToMailText;
	}
	
	@FindBy(xpath="//android.widget.Button[@text='OK']")
	WebElement popUpOkButton;
	public WebElement popUpOkButton()
	{
		return popUpOkButton;
	}

}
